//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.1434
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenVPNManager.lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenVPNManager.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not communicate with OpenVPN Manager - perhaps remote control is not allowed? ähnelt.
        /// </summary>
        internal static string ARGS_Error {
            get {
                return ResourceManager.GetString("ARGS_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -install-autostart   -   Install autostart and quit
        ///-remove-autostart   -   Remove autostart and quit
        ///-connect name   -   Connect to VPN &quot;name&quot;
        ///-disconnect name   -   Disconnect from VPN &quot;name&quot;
        ///-quit   -   Shut down running OpenVPN Manager ähnelt.
        /// </summary>
        internal static string ARGS_Help {
            get {
                return ResourceManager.GetString("ARGS_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid value &quot;{1}&quot; for agrument {0}!
        ///Valid values are:
        ///{2} ähnelt.
        /// </summary>
        internal static string ARGS_Invalid_Parameter {
            get {
                return ResourceManager.GetString("ARGS_Invalid_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing value for argument &quot;{0}&quot; ähnelt.
        /// </summary>
        internal static string ARGS_Missing_Parameter {
            get {
                return ResourceManager.GetString("ARGS_Missing_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown argument &quot;{0}&quot; ähnelt.
        /// </summary>
        internal static string ARGS_Unknown_Parameter {
            get {
                return ResourceManager.GetString("ARGS_Unknown_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to connect!
        ///
        ///Details: ähnelt.
        /// </summary>
        internal static string BOX_Error_Connect {
            get {
                return ResourceManager.GetString("BOX_Error_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while loading configuration: ähnelt.
        /// </summary>
        internal static string BOX_Error_Information {
            get {
                return ResourceManager.GetString("BOX_Error_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find SmartCard. Please insert one and press retry. ähnelt.
        /// </summary>
        internal static string BOX_NoKey {
            get {
                return ResourceManager.GetString("BOX_NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to reconnect to this VPN? ähnelt.
        /// </summary>
        internal static string BOX_Reconnect {
            get {
                return ResourceManager.GetString("BOX_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In order to edit settings all connection must be closed. Close all connections? ähnelt.
        /// </summary>
        internal static string BOX_Settings_Close {
            get {
                return ResourceManager.GetString("BOX_Settings_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The update information could not be downloaded ähnelt.
        /// </summary>
        internal static string BOX_UpdateError {
            get {
                return ResourceManager.GetString("BOX_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The update information hat an invalid format ähnelt.
        /// </summary>
        internal static string BOX_UpdateFormat {
            get {
                return ResourceManager.GetString("BOX_UpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new Version (%s) was found. Do you want to see details in your browser? ähnelt.
        /// </summary>
        internal static string BOX_UpdateInformation {
            get {
                return ResourceManager.GetString("BOX_UpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The update information did not contain this program! ähnelt.
        /// </summary>
        internal static string BOX_UpdateMissing {
            get {
                return ResourceManager.GetString("BOX_UpdateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No new version was found. ähnelt.
        /// </summary>
        internal static string BOX_UpdateNone {
            get {
                return ResourceManager.GetString("BOX_UpdateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All files ähnelt.
        /// </summary>
        internal static string DIALOG_Filter_Allfiles {
            get {
                return ResourceManager.GetString("DIALOG_Filter_Allfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Applications ähnelt.
        /// </summary>
        internal static string DIALOG_Filter_Application {
            get {
                return ResourceManager.GetString("DIALOG_Filter_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select OpenVPN configuration directory ähnelt.
        /// </summary>
        internal static string DIALOG_Title_Folder {
            get {
                return ResourceManager.GetString("DIALOG_Title_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search OpenVPN ähnelt.
        /// </summary>
        internal static string DIALOG_Title_Open_OpenVPN {
            get {
                return ResourceManager.GetString("DIALOG_Title_Open_OpenVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect (Alt+O) ähnelt.
        /// </summary>
        internal static string QUICKINFO_Connect {
            get {
                return ResourceManager.GetString("QUICKINFO_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect (Alt+O) ähnelt.
        /// </summary>
        internal static string QUICKINFO_Disconnect {
            get {
                return ResourceManager.GetString("QUICKINFO_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Update is available! ähnelt.
        /// </summary>
        internal static string QUICKINFO_Update {
            get {
                return ResourceManager.GetString("QUICKINFO_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die See the &quot;about&quot; Dialog for more information. ähnelt.
        /// </summary>
        internal static string QUICKINFO_Update_More {
            get {
                return ResourceManager.GetString("QUICKINFO_Update_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected ähnelt.
        /// </summary>
        internal static string STATE_Connected {
            get {
                return ResourceManager.GetString("STATE_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initializing... ähnelt.
        /// </summary>
        internal static string STATE_Initializing {
            get {
                return ResourceManager.GetString("STATE_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopped ähnelt.
        /// </summary>
        internal static string STATE_Stopped {
            get {
                return ResourceManager.GetString("STATE_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopping... ähnelt.
        /// </summary>
        internal static string STATE_Stopping {
            get {
                return ResourceManager.GetString("STATE_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Connect ähnelt.
        /// </summary>
        internal static string TRAY_Connect {
            get {
                return ResourceManager.GetString("TRAY_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Disconnect ähnelt.
        /// </summary>
        internal static string TRAY_Disconnect {
            get {
                return ResourceManager.GetString("TRAY_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Edit ähnelt.
        /// </summary>
        internal static string TRAY_Edit {
            get {
                return ResourceManager.GetString("TRAY_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show &amp;error information ähnelt.
        /// </summary>
        internal static string TRAY_Error_Information {
            get {
                return ResourceManager.GetString("TRAY_Error_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Show ähnelt.
        /// </summary>
        internal static string TRAY_Show {
            get {
                return ResourceManager.GetString("TRAY_Show", resourceCulture);
            }
        }
    }
}
